server:
  port: 8800
spring:
  profiles:
    active: memory
  application:
    name: concept-plugin-sample
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
concept:
  plugin:
    metadata:
      standard-type: com.github.linyuzai.plugin.jar.concept.JarPlugin.StandardMetadata
    validation:
      max-nested-depth: 5
      max-read-size: 2MB
    storage:
      type: memory
      location: data
      filter-suffixes: .zip,.jar
    autoload:
      enabled: true
      period: 5000
    logger:
      standard:
        enabled: true
    extension:
      request-mapping:
        enabled: true
    management:
      enabled: true
      locale: zh_CN
      authorization:
        password: 123456
      github-corner:
        display: true
      header:
        display: true
        title:
          display: true
          text: "插件管理"
      footer:
        display: true